from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_pdf_report(file_path, dataset_info, kpis, insights, recommendations):
    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    title = Paragraph("Sales Analytics Executive Report", styles["Title"])
    story.append(title)
    story.append(Spacer(1, 18))

    story.append(Paragraph("Dataset Information", styles["Heading2"]))

    dataset_data = [
        ["Dataset", dataset_info.get("filename", "N/A")],
        ["Rows", dataset_info.get("rows", "N/A")],
        ["Columns", dataset_info.get("columns", "N/A")],
        ["Filtered Rows", dataset_info.get("filtered_rows", "N/A")],
        ["Last Updated", dataset_info.get("last_updated", "N/A")]
    ]

    dataset_table = Table(dataset_data, colWidths=[150, 300])
    dataset_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#21459d")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(dataset_table)
    story.append(Spacer(1, 18))

    story.append(Paragraph("KPI Summary", styles["Heading2"]))

    kpi_data = [
        ["Metric", "Value"],
        ["Total Sales", kpis.get("total_sales", "N/A")],
        ["Total Orders", kpis.get("total_orders", "N/A")],
        ["Average Sales", kpis.get("avg_sales", "N/A")],
        ["Total Profit", kpis.get("total_profit", "N/A")],
        ["Profit Margin", kpis.get("profit_margin", "N/A")],
        ["Total Customers", kpis.get("total_customers", "N/A")],
        ["Total Products", kpis.get("total_products", "N/A")],
        ["Top Region", kpis.get("top_region", "N/A")]
    ]

    kpi_table = Table(kpi_data, colWidths=[220, 230])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#21459d")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f5f8ff")),
    ]))

    story.append(kpi_table)
    story.append(Spacer(1, 18))

    story.append(Paragraph("Executive Insights", styles["Heading2"]))

    for insight in insights:
        story.append(Paragraph(f"• {insight}", styles["BodyText"]))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 12))

    story.append(Paragraph("Business Recommendations", styles["Heading2"]))

    for recommendation in recommendations:
        story.append(Paragraph(f"• {recommendation}", styles["BodyText"]))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 25))

    footer = Paragraph(
        "Generated by Sales Analytics Web Dashboard | Python • Flask • Pandas • Plotly",
        styles["Italic"]
    )
    story.append(footer)

    doc.build(story)